# -*- coding: utf-8 -*-
"""request.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Re87khma0Kac8krajginxrD3D2uMgN8Q
"""

@@ -0,0 +1,6 @@
import requests

url = 'http://localhost:5000/predict_api'
r = requests.post(url,json={'experience':2, 'test_score':9, 'interview_score':6})

print(r.json()